apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: bootnode-keys
  options:
    disableNameSuffixHash: true
  files:
    - files/reth-bootnode-p2p.key


helmCharts:
- releaseName: reth-bootnode
  repo: "https://ethpandaops.github.io/ethereum-helm-charts"
  name: reth
  version: 0.0.14
  additionalValuesFiles:
  - reth-bootnode.yaml

